export const books = [
  {
    id: 1,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    price: 11.99,
    inStock: true,
    isFavorite: true,
    genre: "Classic Fiction",
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    price: 13.49,
    inStock: false,
    isFavorite: true,
    genre: "Dystopian Fiction",
  },
  {
    id: 3,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    price: 10.99,
    inStock: true,
    isFavorite: false,
    genre: "Classic Fiction",
  },
  {
    id: 4,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    price: 15.75,
    inStock: true,
    isFavorite: true,
    genre: "Fantasy",
  },
  {
    id: 5,
    title: "Atomic Habits",
    author: "James Clear",
    price: 17.99,
    inStock: false,
    isFavorite: true,
    genre: "Self-Help",
  },
  {
    id: 6,
    title: "Becoming",
    author: "Michelle Obama",
    price: 18.5,
    inStock: true,
    isFavorite: true,
    genre: "Biography",
  },
  {
    id: 7,
    title: "Educated",
    author: "Tara Westover",
    price: 16.0,
    inStock: true,
    isFavorite: false,
    genre: "Memoir",
  },
  {
    id: 8,
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    price: 14.25,
    inStock: false,
    isFavorite: true,
    genre: "Self-Help",
  },
  {
    id: 9,
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    price: 21.99,
    inStock: true,
    isFavorite: true,
    genre: "Non-Fiction",
  },
  {
    id: 10,
    title: "The Midnight Library",
    author: "Matt Haig",
    price: 12.75,
    inStock: true,
    isFavorite: false,
    genre: "Philosophical Fiction",
  },
];
